# Generated by Django 5.2.4 on 2025-08-11 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Complaint",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("user_phone_number", models.CharField(max_length=100)),
                ("user_address", models.TextField()),
                ("complaint_message", models.TextField()),
                ("department", models.CharField(max_length=100)),
                ("raw_conversation", models.TextField()),
                ("raw_complaint_json", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
